app.server.host=127.0.0.1
app.server.port=5000
app.client.input-file=docs/assignment/sample-input-ascii.bin
app.output.file=data/messages.txt
app.database.url=jdbc:sqlite:data/framed-messages.db
app.database.schema=schema.sql
